name: "frontend"
services:
  frontend:
    develop:
      watch:
        - action: rebuild
          path: ./package.json
        - action: sync
          path: .
          target: /frontend
          ignore:
            - node_modules/
