name: "frontend"
services:
  frontend:
    develop:
      watch:
        - action: rebuild
          path: ./frontend/package.json
        - action: sync
          path: ./frontend
          target: /frontend
          ignore:
            - node_modules/
