services:
  api:
    extends:
      file: ./api/docker-compose.${BUILD_TARGET:-production}.yml
      service: api
    build:
      context: ./api/
      dockerfile: Dockerfile
      target: ${BUILD_TARGET:-production}
    env_file:
      - .env
    ports:
      - ${API_PORT:-8000}:${API_PORT:-8000}
  frontend:
    extends:
      file: ./frontend/docker-compose.${BUILD_TARGET:-production}.yml
      service: frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
      target: ${BUILD_TARGET:-production}
    env_file:
      - .env
    ports:
      - ${FRONTEND_PORT:-80}:${FRONTEND_PORT:-80}
    
