name: "docker-executer"
services:
  docker-executer:
    develop:
      watch:
        - action: rebuild
          path: ./requirements.txt
        - action: sync
          path: .
          target: /app
          ignore:
            - requirements.txt
